default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: twittera_postgres
  user: postgres
 
development:
  <<: *default
  database: backend_development
 
test:
  <<: *default
  database: backend_test
 
production:
  <<: *default
  database: backend_production
  username: postgres
  password: <%= ENV['POSTGRES_DATABASE_PASSWORD'] %>