version: "3.9"
services:
  postgres:
    container_name: twittera_postgres
    image: "postgres:9.5"
    volumes:
      - postgres:/var/lib/postgresql/data
 
  redis:
    image: "redis:3.2-alpine"
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis:/var/lib/redis/data
 
  backend:
    depends_on:
      - "postgres"
      - "redis"
    build: ./backend
    command: bash start.sh
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/backend
      - backend-gems:/backend-gems
 
volumes:
  redis:
  postgres:
  backend-gems: